### ISSUE TITLE
Support modules without vendor directory

### ISSUE THREAD

**Issue by skck** [Haehnchen/idea-php-oxid-plugin#2]
Seems like only modules within a vendor directory are supported by the plugin.

`modules/oe/oepaypal/metadata.php` --> Paths are clickable and class inheritance is added to the `.phpstorm-oxid.meta.php` file

`modules/fcPayOne/metadata.php` --> Paths can not be resolved.

![bildschirmfoto 2015-07-14 um 11 45 24](https://cloud.githubusercontent.com/assets/2588308/8670506/10ae134a-2a1e-11e5-8985-2adaf2321c94.png)

It'd be nice to support those modules as well.

**Comment by Haehnchen** [comment]
so i need to check for `vendormetadata.php`. will change the behavior

**Comment by GM-Alex** [comment]
Modules without the vendor directory are still not working with 0.3.1.

**Comment by GM-Alex** [comment]
@Haehnchen Any news for this? Does that work on your environment?

**Comment by Haehnchen** [comment]
@GM-Alex can you give me an example of your directory structure?

**Comment by GM-Alex** [comment]
@Haehnchen I made a mistake, the problem is not related to the metadata.php, it's related to the .phpstorm-oxid.meta.php file. That one contains only modules with a vendor directory and not modules with the following structure:

SHOPROOT/modules/MYAWESOMEMODULE/metadata.php

Should I open a new issue for that?

**Comment by Haehnchen** [comment]
@GM-Alex fixed

**Comment by GM-Alex** [comment]
@Haehnchen Works perfectly now. Thanks a lot!
